### PR TITLE
Feature/rescraperesume

### PR DESCRIPTION
**Pull request by sf2ne**
Changed up the workflow of verification so that it opens the json file each iteration of verification and also dumps to the json file at the end of every iteration. Did some code cleanup and fixed everything I could find was a problem from the merge with develop. Please test it vigorously. Also should I just encompass calling run_verification in a try , except. So that if verification breaks at all during the process it just runs the whole program again? I'd put that in another PR.

### CODE REVIEW

**Comment by sf2ne** [comment]
Lol this isn't really rescrape-resume

**Comment by zamattiac** [comment]
@sf2ne What would you put in the **except** to run the process again?

**Comment by sf2ne** [comment]
@zamattiac I'm not really sure. Like an error message and then just call the method again?

**Comment by zamattiac** [comment]
After full test, there don't seem to be any issues.

**Pull request merged**
